productos:
    resource: "@ProductosBundle/Controller/"
    type:     annotation
    prefix:   /productos

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

app:
    resource: '@AppBundle/Controller/'
    type: annotation



